services:
  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-agent
    restart: always
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./beszel_agent_data:/var/lib/beszel-agent
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
    environment:
      LISTEN: 45876
      KEY: '${BESZEL_KEY}'
      TOKEN: ${BESZEL_TOKEN}
      HUB_URL: https://beszel.gustavocastro.com
    labels:
      - glance.name=beszel-agent
      - glance.icon=sh:beszel
      - glance.description=beszel agent
      - glance.id=beszel-agent