services:
  traefik:
    image: traefik:v3.5.1
    restart: unless-stopped
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
      - traefik_config:/etc/traefik
      - traefik_dynamic:/dynamic
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik
      - default
    labels:
      - homepage.group=Hetzner Two
      - homepage.name=Traefik
      - homepage.icon=traefik.png
      - homepage.description=Traefik Reverse proxy

networks:
  traefik:
    external: true
    
volumes:
  letsencrypt:
  traefik_config:
    external: true
  traefik_dynamic:
    external: true
