services:
  traefik:
    image: traefik:v3.6
    restart: unless-stopped
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
      - traefik_config:/etc/traefik
      - traefik_dynamic:/dynamic
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik
      - default
    labels:
      - glance.name=traefik
      - glance.icon=sh:traefik
      - glance.description=reverse proxy
      - glance.url=https://traefik.gustavocastro.com
      - glance.id=traefik

networks:
  traefik:
    external: true
    
volumes:
  letsencrypt:
  traefik_config:
    external: true
  traefik_dynamic:
    external: true
