services:
  coredns:
    image: coredns/coredns:1.14.0
    restart: unless-stopped
    container_name: coredns
    command: ["-conf", "/config/Corefile"]
    volumes:
      - coredns_config:/config
    ports:
      - "100.104.139.20:53:53/udp"
      - "100.104.139.20:53:53/tcp"
    labels:
      - glance.name=coredns
      - glance.icon=di:coredns
      - glance.description=custom dns for tailnet
      - glance.id=coredns

volumes:
  coredns_config:
    external: true
