services:
  placeholder:
    image: nginx:1.29-alpine
    container_name: placeholder-public
    restart: unless-stopped
    volumes:
      - public_placeholder:/usr/share/nginx/html:ro
    labels:
      - traefik.enable=true
      - traefik.http.services.placeholder-public.loadbalancer.server.port=80
      - glance.name=Public Placeholder
      - glance.icon=si:nginx
      - glance.description=Error page for external subdomain access
      - glance.id=placeholder-public
    networks:
      - traefik

networks:
  traefik:
    external: true

volumes:
  public_placeholder:
    external: true
