- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: bookmarks
          title: Services
          groups:
            - hide-arrow: true
              links:
                - title: Monitoring
                  url: https://beszel.gustavocastro.com/
                  icon: sh:beszel
                - title: Bookmarks
                  url: https://linkwarden.gustavocastro.com/
                  icon: sh:linkwarden
                - title: Files
                  url: https://files.gustavocastro.com/
                  icon: sh:cloudreve
                - title: Paperless
                  url: https://paperless.gustavocastro.com/
                  icon: sh:paperless-ngx
                - title: Documents
                  url: https://papra.gustavocastro.com/
                  icon: sh:papra
                - title: Passwords
                  url: https://bitwarden.gustavocastro.com/
                  icon: sh:bitwarden
                - title: Uptime
                  url: https://uptime.gustavocastro.com/
                  icon: sh:uptime-kuma
                - title: Traefik
                  url: https://traefik.gustavocastro.com/
                  icon: sh:traefik
        - type: bookmarks
          title: Cloud Providers
          groups:
             - links:
                - title: Tailscale
                  url: https://login.tailscale.com/welcome
                - title: Hetzner
                  url: https://console.hetzner.com/projects/11964967/dashboard
                - title: Cloudflare
                  url: https://dash.cloudflare.com/
                - title: Oracle
                  url: https://www.oracle.com/cloud/sign-in.html

    - size: full
      widgets:
        - type: group
          widgets:
            - type: hacker-news
            - type: lobsters
        - type: group
          widgets:
          - type: docker-containers
            title: Hetzner One
            hide-by-default: false
            sock-path: tcp://10.0.0.3:2375
          - type: docker-containers
            title: Hetzner Two
            hide-by-default: false
    - size: small
      widgets:
        - type: weather
          location: Amsterdam
          units: metric
          hour-format: 24h
        - type: clock
          hour-format: 24h
          timezones:
            - timezone: America/Sao_Paulo
              label: SÃ£o Paulo