services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    container_name: homepage
    ports:
      - 10.0.0.3:3000:3000
    volumes:
      - homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HOMEPAGE_ALLOWED_HOSTS: home.gustavocastro.com
    labels:
      - homepage.group=Hetzner One
      - homepage.name=Homepage
      - homepage.icon=homepage.png
      - homepage.href=https://home.gustavocastro.com/
      - homepage.description=Homepage

volumes:
  homepage:
    external: true
