services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - beszel_data:/beszel_data
      - beszel_socket:/beszel_socket
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.beszel.rule=Host(`beszel.gustavocastro.com`)
      - traefik.http.routers.beszel.entrypoints=web,websecure
      - traefik.http.routers.beszel.tls=true
      - traefik.http.services.beszel.loadbalancer.server.port=8090
      - glance.name=beszel
      - glance.icon=sh:beszel
      - glance.url=https://beszel.gustavocastro.com
      - glance.description=server monitoring
      - glance.id=beszel
  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - beszel_agent_data:/var/lib/beszel-agent
      - beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: http://localhost:8090
      TOKEN: ${BESZEL_TOKEN}
      KEY: "${BESZEL_KEY}"
    labels:
      - glance.name=beszel-agent
      - glance.parent=beszel

volumes:
  beszel_data:
    external: true
  beszel_agent_data:
    external: true
  beszel_socket:
    external: true

networks:
  traefik:
    external: true