services:
  n8n:
    image: n8nio/n8n:1.118.2
    restart: unless-stopped
    ports:
      - 5678:5678
    container_name: n8n
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE="Europe/Amsterdam"
      - TZ="Europe/Amsterdam"
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    labels:
      - homepage.group=Hetzner One
      - homepage.name=n8n
      - homepage.icon=n8n.png
      - homepage.href=https://n8n.gustavocastro.com/
      - homepage.description=Workflow Automation

volumes:
  n8n_data:
    external: true