---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Bookmarks:
    - Tailscale:
        - icon: si-tailscale
          href: https://login.tailscale.com/welcome
    - Hetzner:
        - icon: hetzner
          href: https://console.hetzner.com/projects/11964967/dashboard
    - AWS:
        - icon: amazon-web-services
          href: https://console.aws.amazon.com/
    - Oracle:
        - icon: oracle
          href: https://www.oracle.com/cloud/sign-in.html
    - Cloudflare:
        - icon: cloudflare
          href: https://dash.cloudflare.com/
    - Github:
        - icon: github
          href: https://github.com/gcstr/homeserver/