title: Home
theme: dark
color: slate
startUrl: http://home.gustavocastro.com
iconStyle: theme
headerStyle: clean
disableCollapse: true
hideVersion: true
showStats: true
background:
  #image: https://images.unsplash.com/photo-1475070929565-c985b496cb9f?auto=format&fit=crop&w=2560&q=80
  #image: https://images.unsplash.com/photo-1477346611705-65d1883cee1e?auto=format&fit=crop&w=2560&q=80
  #image: https://images.unsplash.com/photo-1563387852576-964bc31b73af?auto=format&fit=crop&w=2560&q=80
  image: https://images.unsplash.com/photo-1485470733090-0aae1788d5af?auto=format&fit=crop&w=2560&q=80
  #blur: sm
  brightness: 50
cardBlur: md

layout:
  Hetzner One:
    style: row
    columns: 3
    useEqualHeights: true 
  Hetzner Two:
    style: row
    columns: 3
    useEqualHeights: true
  Bookmarks:
    style: row
    columns: 3
    useEqualHeights: true